# Generated by Django 4.2.6 on 2023-11-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_orderitem_food_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='restaurant.food'),
            preserve_default=False,
        ),
    ]
